CREATE TABLE "GCG_6087_SETTINGS" (
 "ID" IDENTITY DEFAULT '0' CONSTRAINT "UK_ID" UNIQUE USING 0,
 "MAIL_SERVER" LONGVARCHAR,
 "MAIL_PORT" INTEGER,
 "EMAIL" LONGVARCHAR,
 "EMAIL_PASSWORD" BINARY(20),
 "ATTACH_PATH" LONGVARCHAR,
 "SENDER_EMAIL" LONGVARCHAR );